name: deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            command: deploy --name ${{ secrets.WORKER_NAME }}
